name: Deploy FastAPI (App Service code deploy)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ※ ZIPデプロイはサーバー側(Oryx)でビルドするので
      #    ここで仮想環境を作ったりpip installは不要（テストしたいなら別途）
      #    必要なのは「backendフォルダをそのまま固めて渡す」こと。
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: ./backend

      - name: Deploy to Azure Web App (ZIP/OneDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-py-oshima33'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9CE0055835FD44F3AF7B880B5FA9AAC4 }}
          package: ./backend
