name: Deploy FastAPI to Azure App Service (root)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la   # ← ここで main.py/requirements.txt が見えることを確認

      - name: Deploy to Azure Web App (ZIP/OneDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-2-py-oshima13'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9CE0055835FD44F3AF7B880B5FA9AAC4 }}
          package: .

